# Generated by Django 4.2 on 2024-09-25 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('income', models.IntegerField()),
                ('expenditure', models.IntegerField()),
                ('category', models.CharField(choices=[('ALLOWANCE', '용돈'), ('BONUS', '추가 용돈'), ('CHORES_EARNINGS', '용돈 벌이'), ('PRIZES', '상금/포상금'), ('SNACK', '간식비'), ('TOYS', '게임/장난감비'), ('BOOKS', '책/학용품비'), ('TRANSPORT', '교통비'), ('EXTRACURRICULAR', '학원비'), ('ENTERTAINMENT', '문화/오락비'), ('GIFT', '선물비')], max_length=20)),
                ('public', models.BooleanField(default=True)),
                ('today', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
