# Generated by Django 4.2 on 2024-09-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('food_expense', models.PositiveIntegerField()),
                ('transportation_expense', models.PositiveIntegerField()),
                ('savings', models.PositiveIntegerField()),
                ('snack_expense', models.PositiveIntegerField()),
                ('plan_details', models.TextField()),
                ('allowance_plan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
