# Generated by Django 4.2 on 2024-09-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financediary',
            name='public',
        ),
    ]
