# Generated by Django 4.2 on 2024-10-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_monthlysummary_delete_mothlysummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysummary',
            old_name='encouragement_message',
            new_name='encouragement',
        ),
    ]
