# Generated by Django 4.2 on 2024-10-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encouragement',
            field=models.TextField(blank=True, help_text='부모님이 자녀에게 남기는 격려 메시지', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', help_text='프로필 이미지', null=True, upload_to='profile_images/'),
        ),
    ]
