# Generated by Django 4.2 on 2024-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_images_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.TextField(blank=True, help_text='프로필 이미지', null=True),
        ),
    ]
